# Generated by Django 5.1.6 on 2026-05-31 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_public_key', models.CharField(blank=True, default='', max_length=200)),
                ('stripe_secret_key', models.CharField(blank=True, default='', max_length=200)),
                ('stripe_webhook_secret', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'verbose_name': 'Configuración del sitio',
            },
        ),
        migrations.AlterModelOptions(
            name='membership',
            options={'verbose_name': 'membresía', 'verbose_name_plural': 'membresías'},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'verbose_name': 'plan', 'verbose_name_plural': 'planes'},
        ),
    ]
