# Generated by Django 5.1.6 on 2026-06-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_siteconfig_alter_membership_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='notification_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
