# Generated by Django 5.1.6 on 2026-06-30 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0004_add_affiliate'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False),
        ),
    ]
