# Generated by Django 5.1.6 on 2026-05-31 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'notificación', 'verbose_name_plural': 'notificaciones'},
        ),
    ]
