# Generated by Django 5.1.6 on 2026-06-26 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('comment', 'Comentario'), ('like', 'Like'), ('event', 'Evento'), ('system', 'Sistema'), ('post', 'Publicación'), ('course', 'Curso'), ('lesson', 'Lección')], max_length=20),
        ),
    ]
