# Generated by Django 5.1.6 on 2026-05-31 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_alter_category_options_category_color_category_icon_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'name'], 'verbose_name': 'categoría', 'verbose_name_plural': 'categorías'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at'], 'verbose_name': 'comentario', 'verbose_name_plural': 'comentarios'},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name': 'me gusta', 'verbose_name_plural': 'me gustas'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-is_pinned', '-created_at'], 'verbose_name': 'publicación', 'verbose_name_plural': 'publicaciones'},
        ),
    ]
