# Generated by Django 5.1.6 on 2026-06-27 09:22

import apps.classroom.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_comment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postattachment',
            name='file',
            field=models.FileField(upload_to='post_attachments/', validators=[apps.classroom.models.validate_file_extension]),
        ),
    ]
