# Generated by Django 5.1.6 on 2026-06-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_options_alter_eventattendee_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='banner_image',
            field=models.URLField(blank=True, help_text='URL de imagen de portada del evento'),
        ),
    ]
