# Generated by Django 5.1.6 on 2026-05-31 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaderboardpoint',
            options={'ordering': ['-created_at'], 'verbose_name': 'punto de clasificación', 'verbose_name_plural': 'puntos de clasificación'},
        ),
    ]
