# Generated by Django 5.1.6 on 2026-07-23 09:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0002_alter_leaderboardpoint_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='leaderboardpoint',
            constraint=models.UniqueConstraint(fields=('user', 'action', 'reference_id'), name='unique_point_per_user_action_reference'),
        ),
    ]
