# Generated by Django 5.1.6 on 2026-05-31 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_last_seen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'verbose_name': 'usuario', 'verbose_name_plural': 'usuarios'},
        ),
    ]
