# Generated by Django 5.1.6 on 2026-05-31 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='The Hackers Labs Academy', max_length=120)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='site/')),
            ],
            options={
                'verbose_name': 'Configuración del sitio',
            },
        ),
    ]
