# Generated by Django 5.1.6 on 2026-06-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_courses',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_testimonials',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
