# Generated by Django 5.1.6 on 2026-06-20 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_accent_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='presentation_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
