# Generated by Django 5.1.6 on 2026-06-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_add_presentation_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='community_description',
            field=models.CharField(blank=True, default='Aprende ciberseguridad con una comunidad activa. Cursos, retos CTF, eventos y networking.', max_length=300),
        ),
    ]
