# Generated by Django 5.1.6 on 2026-05-31 15:30

import apps.classroom.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_lessonattachment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['order', 'title'], 'verbose_name': 'curso', 'verbose_name_plural': 'cursos'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order'], 'verbose_name': 'lección', 'verbose_name_plural': 'lecciones'},
        ),
        migrations.AlterModelOptions(
            name='lessonattachment',
            options={'ordering': ['uploaded_at'], 'verbose_name': 'adjunto de lección', 'verbose_name_plural': 'adjuntos de lección'},
        ),
        migrations.AlterModelOptions(
            name='lessonprogress',
            options={'verbose_name': 'progreso de lección', 'verbose_name_plural': 'progresos de lección'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order'], 'verbose_name': 'módulo', 'verbose_name_plural': 'módulos'},
        ),
        migrations.AlterField(
            model_name='lessonattachment',
            name='file',
            field=models.FileField(upload_to='attachments/lessons/%Y/%m/', validators=[apps.classroom.models.validate_file_size]),
        ),
    ]
