# Generated by Django 5.1.6 on 2026-05-31 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_alter_course_options_alter_lesson_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='is_premium',
        ),
    ]
