# Generated by Django 5.1.6 on 2026-06-27 09:22

import apps.classroom.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonattachment',
            name='file',
            field=models.FileField(upload_to='attachments/lessons/%Y/%m/', validators=[apps.classroom.models.validate_file_size, apps.classroom.models.validate_file_extension]),
        ),
    ]
