# Generated by Django 5.1.6 on 2026-05-31 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-updated_at'], 'verbose_name': 'conversación', 'verbose_name_plural': 'conversaciones'},
        ),
        migrations.AlterModelOptions(
            name='directmessage',
            options={'ordering': ['created_at'], 'verbose_name': 'mensaje directo', 'verbose_name_plural': 'mensajes directos'},
        ),
    ]
